pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./array.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; REFERENCE TYPES &#62; ARRAY","ARRAY Navigation: AMAZON JUNIOR SOFTWARE DEVELOPER GETTING STARTED WITH JAVA DATA TYPES REFERENCE TYPES ARRAY ",""],
["./classes.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; CLASSES","A class is an archetype or code structure that contains the behavior, properties and methods of a particular object.",""],
["./concatenation.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; CONCATENATION","Concatenation is the process of linking two or more strings into one string. To concatenate strings the &#39;+&#39; symbol is used as connectors.",""],
["./control-flow-statements-and-lo.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; CONTROL FLOW: STATEMENTS AND LOOPS","CONTROL FLOW: STATEMENTS AND LOOPS Navigation: AMAZON JUNIOR SOFTWARE DEVELOPER INTRODUCTION TO SOFTWARE DEVELOPMENT CONTROL FLOW: STATEMENTS AND ...",""],
["./data-structures.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA STRUCTURES","Data Structure Description Usage Array Fixed-size sequential data storage Used for storing multiple values of the same type ArrayList Resizable dy...",""],
["./data-types.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; VARIABLES","Variables are a nominal storage location for specific values or data. To declare a variable, a name and type most be given to it:",""],
["./features.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; FEATURES","WORA, write once, run anywhere (cross-platform).  Error-handled  Garbage collected.",""],
["./final-project-and-assessment-i.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; FINAL PROJECT AND ASSESSMENT","FINAL PROJECT AND ASSESSMENT Navigation: AMAZON JUNIOR SOFTWARE DEVELOPER INTRODUCTION TO SOFTWARE DEVELOPMENT FINAL PROJECT AND ASSESSMENT ",""],
["./getting-started-with-java.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA","Java is a cross-platform, generic, object-oriented, functional, imperative, reflective, concurrent programming language released by Sun Microsyste...",""],
["./learning-points.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; SOME CONCEPTS","Explain the advantages of using an IDE. Integrated development environments, or IDE&#39;s for short, are application software that helps write, debug,...",""],
["./object-oriented-programming-ba.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; OBJECT-ORIENTED PROGRAMMING BASICS","OBJECT-ORIENTED PROGRAMMING BASICS Navigation: AMAZON JUNIOR SOFTWARE DEVELOPER INTRODUCTION TO SOFTWARE DEVELOPMENT OBJECT-ORIENTED PROGRAMMING B...",""],
["./objects.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; OBJECTS","An object is an unit of data that represents a real-world entity or concept, with its data (properties) and functions (methods).",""],
["./operators.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; OPERATORS","Operators are special symbols or keywords that allow to perform operations with values, variables or expressions. Operators can be of arithmetic, ...",""],
["./primitive.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES","Data Type Size (bits) Default Value Description byte 8 0 Stores small integers (-128 to 127). short 16 0 Stores medium-range integers (-32,768 to ...",""],
["./reference.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; REFERENCE TYPES","Data Type Size (bits) Default Value Description Array Varies null Stores a collection of elements of the same type. Class (Object) Varies null Sto...",""],
["./string.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; STRING","A String is a sequence of characters wrapped up into an Object. Strings are immutable, which makes it impossible to change their value at runtime ...",""],
["./text-case.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; TEXT CASE","Comprise string methods that change the way letters in a string are represented in terms of their toUpperCase() (capital letters) toLowerCase(); (...",""],
["./the-charat-method.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; THE charAt() METHOD","Returns the character at the specified location, for example:",""],
["./the-length-method.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; THE length() METHOD","Returns the integer representing the number of characters contained in a string. For example:",""],
["./usage.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; GETTING STARTED WITH JAVA &#62; USAGE","Enterprise-level applications, such as CRM and ERP, and web applications, most Android apps and desktop-level applications, such as media players,...",""]];
