pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./classes.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; CLASSES","A class is an archetype or code structure that contains the behavior, properties and methods of a particular object.",""],
["./data-types.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; VARIABLES","Variables are a nominal storage location for specific values or data. To declare a variable, a name and type most be given to it:",""],
["./features.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; FEATURES","WORA, write once, run anywhere (cross-platform).  Error-handled  Garbage collected.",""],
["./getting-started-with-java.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA","Java is a cross-platform, generic, object-oriented, functional, imperative, reflective, concurrent programming language released by Sun Microsyste...",""],
["./objects.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; OBJECTS","An object is an unit of data that represents a real-world entity or concept, with its data (properties) and functions (methods).",""],
["./operators.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; OPERATORS","Operators are special symbols or keywords that allow to perform operations with values, variables or expressions. Operators can be of arithmetic, ...",""],
["./primitive.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES","Data Type Size (bits) Default Value Description byte 8 0 Stores small integers (-128 to 127). short 16 0 Stores medium-range integers (-32,768 to ...",""],
["./reference.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; REFERENCE TYPES","Data Type Size (bits) Default Value Description Array Varies null Stores a collection of elements of the same type. Class (Object) Varies null Sto...",""],
["./string.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; STRING","A String is a sequence of characters wrapped up into an Object. Strings are immutable, which makes it impossible to change their value at runtime ...",""],
["./the-charat-method.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; THE charAt() METHOD","Returns the character at the specified location, for example:",""],
["./the-length-method.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; DATA TYPES &#62; PRIMITIVE TYPES &#62; THE length() METHOD","Returns the integer representing the number of characters contained in a string. For example:",""],
["./usage.html","AMAZON JUNIOR SOFTWARE DEVELOPER &#62; INTRODUCTION TO SOFTWARE DEVELOPMENT &#62; GETTING STARTED WITH JAVA &#62; USAGE","Enterprise-level applications, such as CRM and ERP, and web applications, most Android apps and desktop-level applications, such as media players,...",""]];
